# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# PaperStream MCP Server - Distributed BERTScore & Scientific Visualization
FROM python:3.12-slim

# Install system dependencies for ML libraries
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libffi-dev \
    libssl-dev \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy dependency files first for better caching
COPY pyproject.toml ./
COPY src/ ./src/

# Install pip and project dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir \
    fastmcp \
    starlette \
    uvicorn \
    pyyaml \
    python-dotenv \
    pydantic \
    httpx \
    aiohttp \
    transformers \
    pillow \
    aiosqlite \
    pymupdf \
    numpy \
    && pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu

# Copy remaining project files
COPY . .

# Create necessary directories (models will be mounted as volume)
RUN mkdir -p data/images data/papers

# Make start script executable
RUN chmod +x start_server.sh

# Expose HTTP port (default from config.yaml)
EXPOSE 8089

# Environment variables with defaults
ENV PAPERSTREAM_HOST=0.0.0.0
ENV PAPERSTREAM_PORT=8089
ENV SD_API_URL=http://host.docker.internal:7860
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app/src

# Volume mounts for persistent data and models
# Models: Mount local models directory to avoid re-downloading
# Data: Mount for persistent database and papers
VOLUME ["/app/src/paperstream/models", "/app/data"]

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
    CMD curl -f http://localhost:8089/health || exit 1

# Default command runs integrated server
# Use: docker run ... paperstream stdio - for stdio mode (MCP)
CMD ["python", "-m", "uvicorn", "src.paperstream.server_integrated:app", \
    "--host", "0.0.0.0", "--port", "8089"]
